CREATE TABLE users (
    id INTEGER primary key generated by default as identity,
    fullname TEXT NOT NULL,
    username TExT NOT NULL UNIQUE,
    password TEXT, 
    nickname TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT now()
);